// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollApp.Models;

namespace PayrollApp.Migrations
{
    [DbContext(typeof(PayrollContext))]
    [Migration("20200709224013_InnitialCreate")]
    partial class InnitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("PayrollApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Salary")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PayrollApp.Models.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AfpRetention")
                        .HasColumnType("REAL");

                    b.Property<double>("ArsRetention")
                        .HasColumnType("REAL");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IsrRetention")
                        .HasColumnType("REAL");

                    b.Property<double>("NetSalary")
                        .HasColumnType("REAL");

                    b.Property<double>("RawSalary")
                        .HasColumnType("REAL");

                    b.Property<double>("TaxableSalary")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Payrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
